export const newsList = [
  {
    "id": 1,
    "title": "公司青年项目在第六届浙江省青工创新创效大赛中荣获金奖",
    "description": "近日，共青团浙江省委、浙江省国资委、浙江省科技厅联合发文公布第六届浙江省青工创新创效大赛结果，经资格审查...",
    "image": "https://img01.yzcdn.cn/vant/cat.jpeg",
    "url": "https://example.com/news1",
    "router": "article"
  },
  {
    "id": 2,
    "title": "科技巨头发布最新智能手机",
    "description": "某科技公司今天发布了他们的新款智能手机，搭载了最新的处理器和相机技术。",
    "image": "https://img01.yzcdn.cn/vant/logo.png",
    "url": "https://example.com/news2",
    "router": "article"
  },
  {
    "id": 3,
    "title": "经济复苏信号显现",
    "description": "多项经济指标显示出复苏的迹象，分析师对未来的经济前景持乐观态度。",
    "image": "https://static.wikia.nocookie.net/fcs-vs-battle/images/3/35/ASDFGuy_Vector.png/revision/latest?cb=20201113171318",
    "url": "https://example.com/news3",
    "router": "article"
  },
  {
    "id": 4,
    "title": "重大科学发现：新型疫苗研发成功",
    "description": "科学家们宣布，他们成功研发出一种新型疫苗，能够有效抵抗多种病毒。",
    "image": "https://www.aplpackaging.co.uk/wp-content/uploads/2019/12/mailingbox-brown-310x240x114-000-300x300.jpg",
    "url": "https://example.com/news4",
    "router": "article"
  },
  {
    "id": 5,
    "title": "全球艺术博览会即将开幕",
    "description": "各国艺术家齐聚一堂，展示他们的最新作品，展览将持续一周。",
    "image": "https://img01.yzcdn.cn/vant/cat.jpeg",
    "url": "https://example.com/news5",
    "router": "article"
  }
];

export const columnList = [
  {title: '论文集'},
  {title: '课题集'},
  {title: '专辑', subtitle: '新质生产力'},
]

export const articleListApiData = {
  "status": 1,
  "message": "success",
  "data": {
      "pageSize": 10,
      "pageIndex": 0,
      "total": 5,
      "data": [
        {
            "id": 1040527,
            "siteID": 219,
            "contentTypeID": "Article",
            "title": "测试视频",
            "titleStyle": "{\"color\":\"\"}",
            "shortTitleStyle": "{\"color\":\"rgba(0, 0, 0, 1)\"}",
            "author": "袁徐丰",
            "editor": "袁徐丰",
            "summary": "测试视频",
            "content": null,
            "linkFlag": "N",
            "status": 30,
            "keyword": null,
            "hitCount": 0,
            "publishDate": "2024-10-07 11:45:20",
            "source": null,
            "sourceURL": null,
            "statusName": "已发布",
            "addTime": "2024-10-07 11:45:20",
            "addUser": "yz0314",
            "url": null,
            "link": "http://zcms.nbport.com.cn:8088/zcms/ui/preview/content/1040527?platformID=pc",
            "catalogID": 19115,
            "catalogName": "论文集",
            "logoFile": "http://zcms.nbport.com.cn:8088/zcms/api/preview/jwb/upload/resources/image/2024/10/07/405507_260x195.png?token=Bearer Ab_60Q70GEBto5PVwQQ1SJUAAAGSZLXxAAVhZG1pbkvnP-4",
            "quantity": 0,
            "templateFlag": "N",
            "template": "",
            "referName": null,
            "referURL": null,
            "relativeContent": null,
            "recommendBlock": null,
            "copyType": "0",
            "copyID": 0,
            "stickTime": 0,
            "publishFlag": "Y",
            "priority": "1",
            "isLock": null,
            "lockUser": null,
            "tag": "",
            "clusterSource": null,
            "clusterTarget": null,
            "contributeFlag": null,
            "contributeUID": 0
        },
        {
            "id": 1040410,
            "siteID": 219,
            "contentTypeID": "Article",
            "title": "【测试】关于开展生物燃料油常态化供应的研究（j建议修订版）-袁徐丰",
            "titleStyle": "{\"color\":\"\"}",
            "shortTitleStyle": "{\"color\":\"rgba(0, 0, 0, 1)\"}",
            "author": "袁徐丰",
            "editor": "袁徐丰",
            "summary": " 【测试】关于开展生物燃料油常态化供应的研究（j建议修订版）",
            "content": null,
            "linkFlag": "N",
            "status": 60,
            "keyword": "视频",
            "hitCount": 0,
            "publishDate": "2024-10-07 11:25:40",
            "source": null,
            "sourceURL": null,
            "statusName": "重新编辑",
            "addTime": "2024-10-07 11:25:40",
            "addUser": "yz0314",
            "url": null,
            "link": "http://zcms.nbport.com.cn:8088/zcms/ui/preview/content/1040410?platformID=pc",
            "catalogID": 19115,
            "catalogName": "论文集",
            "logoFile": "http://zcms.nbport.com.cn:8088/zcms/api/preview/jwb/upload/resources/image/2024/10/07/405504_260x195.png?token=Bearer Ab_60Q70GEBto5PVwQQ1SJUAAAGSZLXxAAVhZG1pbkvnP-4",
            "quantity": 0,
            "templateFlag": "N",
            "template": "",
            "referName": null,
            "referURL": null,
            "relativeContent": null,
            "recommendBlock": null,
            "copyType": "0",
            "copyID": 0,
            "stickTime": 0,
            "publishFlag": "Y",
            "priority": "1",
            "isLock": null,
            "lockUser": null,
            "tag": ",pdf,sp,",
            "clusterSource": null,
            "clusterTarget": null,
            "contributeFlag": null,
            "contributeUID": 0
        },
        {
            "id": 1040402,
            "siteID": 219,
            "contentTypeID": "Article",
            "title": "附件测试",
            "titleStyle": "{\"color\":\"\"}",
            "shortTitleStyle": "{\"color\":\"rgba(0, 0, 0, 1)\"}",
            "author": "系统管理员",
            "editor": "系统管理员",
            "summary": "附件测试",
            "content": null,
            "linkFlag": "N",
            "status": 30,
            "keyword": null,
            "hitCount": 3,
            "publishDate": "2024-10-07 10:38:28",
            "source": null,
            "sourceURL": null,
            "statusName": "已发布",
            "addTime": "2024-10-07 10:38:28",
            "addUser": "admin",
            "url": null,
            "link": "http://zcms.nbport.com.cn:8088/zcms/ui/preview/content/1040402?platformID=pc",
            "catalogID": 19115,
            "catalogName": "论文集",
            "logoFile": null,
            "quantity": 0,
            "templateFlag": "N",
            "template": "",
            "referName": null,
            "referURL": null,
            "relativeContent": null,
            "recommendBlock": null,
            "copyType": "0",
            "copyID": 0,
            "stickTime": 0,
            "publishFlag": "Y",
            "priority": "1",
            "isLock": null,
            "lockUser": null,
            "tag": "",
            "clusterSource": null,
            "clusterTarget": null,
            "contributeFlag": null,
            "contributeUID": 0
        },
        {
            "id": 1040395,
            "siteID": 219,
            "contentTypeID": "Article",
            "title": "关于开展生物燃料油常态化供应的研究-袁徐丰",
            "titleStyle": "{\"color\":\"\"}",
            "shortTitleStyle": "{\"color\":\"rgba(0, 0, 0, 1)\"}",
            "author": "袁徐丰",
            "editor": "袁徐丰",
            "summary": "【个人课题】关于开展生物燃料油常态化供应的研究",
            "content": null,
            "linkFlag": "N",
            "status": 30,
            "keyword": null,
            "hitCount": 2,
            "publishDate": "2024-10-07 10:02:15",
            "source": null,
            "sourceURL": null,
            "statusName": "已发布",
            "addTime": "2024-10-07 10:02:36",
            "addUser": "yz0314",
            "url": null,
            "link": "http://zcms.nbport.com.cn:8088/zcms/ui/preview/content/1040395?platformID=pc",
            "catalogID": 19115,
            "catalogName": "论文集",
            "logoFile": "http://zcms.nbport.com.cn:8088/zcms/api/preview/jwb/upload/resources/image/2024/10/07/405491_260x195.jpg?token=Bearer Ab_60Q70GEBto5PVwQQ1SJUAAAGSZLXxAAVhZG1pbkvnP-4",
            "quantity": 0,
            "templateFlag": "N",
            "template": "",
            "referName": null,
            "referURL": null,
            "relativeContent": null,
            "recommendBlock": null,
            "copyType": "0",
            "copyID": 0,
            "stickTime": 2,
            "publishFlag": "Y",
            "priority": "1",
            "isLock": null,
            "lockUser": null,
            "tag": "",
            "clusterSource": null,
            "clusterTarget": null,
            "contributeFlag": null,
            "contributeUID": 0
        },
        {
            "id": 1040389,
            "siteID": 219,
            "contentTypeID": "Article",
            "title": "测试新闻0930",
            "titleStyle": "{\"color\":\"\"}",
            "shortTitleStyle": "{\"color\":\"rgba(0, 0, 0, 1)\"}",
            "author": "系统管理员",
            "editor": "系统管理员",
            "summary": "1111ssss2222",
            "content": null,
            "linkFlag": "N",
            "status": 60,
            "keyword": "境外",
            "hitCount": 5,
            "publishDate": "2024-09-30 17:25:58",
            "source": null,
            "sourceURL": null,
            "statusName": "重新编辑",
            "addTime": "2024-09-30 17:25:57",
            "addUser": "admin",
            "url": null,
            "link": "http://zcms.nbport.com.cn:8088/zcms/ui/preview/content/1040389?platformID=pc",
            "catalogID": 19115,
            "catalogName": "论文集",
            "logoFile": "http://zcms.nbport.com.cn:8088/zcms/api/preview/jwb/upload/resources/image/2024/10/06/405488_260x195.jpg?token=Bearer Ab_60Q70GEBto5PVwQQ1SJUAAAGSZLXxAAVhZG1pbkvnP-4",
            "quantity": 0,
            "templateFlag": "N",
            "template": "",
            "referName": null,
            "referURL": null,
            "relativeContent": null,
            "recommendBlock": null,
            "copyType": "0",
            "copyID": 0,
            "stickTime": 0,
            "publishFlag": "Y",
            "priority": "1",
            "isLock": null,
            "lockUser": null,
            "tag": ",测试,",
            "clusterSource": null,
            "clusterTarget": null,
            "contributeFlag": null,
            "contributeUID": 0,
            "extend": "{\"file3\":\"upload/resources/file/2024/10/07/405499.pdf?oldName=浙港通web网页端.pdf\",\"file1\":null,\"file2\":null}"
        }
      ]
  }
};

export const articleInfo = {
  1040395: {
    "status": 1,
    "message": "success",
    "data": {
        "id": 1040410,
        "siteID": 219,
        "contentTypeID": "Article",
        "title": "【测试】关于开展生物燃料油常态化供应的研究（j建议修订版）-袁徐丰",
        "titleStyle": "{\"color\":\"\"}",
        "shortTitleStyle": "{\"color\":\"rgba(0, 0, 0, 1)\"}",
        "author": "袁徐丰",
        "editor": "袁徐丰",
        "summary": " 【测试】关于开展生物燃料油常态化供应的研究（j建议修订版）",
        "content": "<p>&nbsp;【测试】关于开展生物燃料油常态化供应的研究（j建议修订版）-袁徐丰</p >",
        "linkFlag": "N",
        "status": 30,
        "keyword": null,
        "hitCount": 0,
        "publishDate": "2024-10-07 11:25:40",
        "source": null,
        "sourceURL": null,
        "statusName": "初稿",
        "addTime": "2024-10-07 11:25:40",
        "addUser": "yz0314",
        "url": null,
        "link": "http://zcms.nbport.com.cn:8088/zcms/ui/content/show?ID=1040410&platformID=pc",
        "catalogID": 19115,
        "catalogName": "论文集",
        "logoFile": "https://www.nbport.com.cn/jwb/upload/resources/image/2024/10/07/405504_260x195.png",
        "quantity": 0,
        "templateFlag": "N",
        "template": "",
        "referName": null,
        "referURL": null,
        "relativeContent": null,
        "recommendBlock": null,
        "copyType": "0",
        "copyID": 0,
        "stickTime": 0,
        "publishFlag": "Y",
        "priority": "1",
        "isLock": null,
        "lockUser": null,
        "tag": "[]",
        "clusterSource": null,
        "clusterTarget": null,
        "contributeFlag": null,
        "contributeUID": 0,
        "extend": "{\"file3\":null,\"file1\":\"upload/resources/file/2024/10/07/405503.pdf?oldName=关于开展生物燃料油常态化供应的研究（j建议修订版）-袁徐丰.pdf\",\"file2\":null}"
    }
  }
}